#!/bin/sh
cd .. 1>/dev/null ||  exit 1
ROOTDIR=$(pwd)
export ROOTDIR
cd - 1>/dev/null || exit 1
PKGNAM=slint-installer
export PKGNAM
KVER=6.12.47
export KVER
SLACKROOT="/data/repos/salix-15.0"
export SLACKROOT
SLACKREPO="$SLACKROOT"/slackware64
export SLACKREPO
PATCHES="$SLACKROOT"/patches/packages
export PATCHES
SLINTROOT=/repo/x86_64/slint-15.0
export SLINTROOT
SLINTREPO="$SLINTROOT"/slint
export SLINTREPO
ARCH="$(uname -m)"
export ARCH
SOURCE="/repo/x86_64/slint-15.0/source"
export SOURCE
ISOVERSION="15.0-beta2"
export ISOLABEL
ISOLABEL="slintsalix$ISOVERSION"
export ISOLABEL
SLINTVERSION="15.0"
export SLINTVERSION
SLACKVERSION="15.0"
export SLACKVERSION
REGULARUSER="$(stat -c %U "$(pwd)")"
export REGULARUSER
DEST="$ROOTDIR"/initrd-tree
export DEST
ISODIR=/home/didier/iso64salix
export ISODIR
SCRIPTS="$ROOTDIR"/misc
export SCRIPTS
DATESTAMP="$(date -u +%Y%m%d)"
export DATESTAMP
PATHTOISO=/repo/x86_64/slint-15.0/slintsalix/slintsalix64-"${ISOVERSION}".iso
export PATHTOISO
INSTALLERVERSION=15.0
export INSTALLERVERSION
SLINTDOCS="$ROOTDIR/slint-translations"
export SLINTDOCS
export LANG=C
SETS="bootstrapsalix aaa_base aaa core efi basic efi-gui fullsalix settings slintsalix"
export SETS
MINSETS="bootstrapsalix aaa_base aaa core efi basic efi-gui fullsalix settings"
export MINSETS
DISTRIBUTION=salix
export DISTRIBUTION
