#!/bin/sh

# This script has been written from scratch and dedicated to the public
# domain by its author: Didier Spaier, 5 place Violet 75015 Paris.

# Anyone is free to copy, modify, publish, use, sell, or distribute it
# for any purpose, commercial or non-commercial, and by any means.
#
# In jurisdictions that recognize copyright laws, the author or authors
# of this software dedicate any and all copyright interest in the
# software to the public domain. We make this dedication for the benefit
# of the public at large and to the detriment of our heirs and
# successors. We intend this dedication to be an overt act of
# relinquishment in perpetuity of all present and future rights to this
# software under copyright law.

# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
# EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
# MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
# IN NO EVENT SHALL THE AUTHORS BE LIABLE FOR ANY CLAIM, DAMAGES OR
# OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE,
# ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
# OTHER DEALINGS IN THE SOFTWARE.
#
# For more information, please refer to <http://unlicense.org/>
# 24/12/2025: function selectcontent added and installfromweb disabled.
# installformweb should be re-written and simplified using slap-get.

echo "salix" > /tmp/distro
echo "aaa
core
efi
basic
efi-gui
fullsalix
settings
slintsalix" > /tmp/set
sed -i 's@Slint@Salix@g' /sbin/functions
sed -i 's@Slint@Salix@g' /etc/rc.d/rc.S
umount /SLINT/* 2>/dev/null
umount /SLINT 2>/dev/null
rmdir /SLINT 2>/dev/null
mkdir /SLINT
rm -rf /INSTALLER
mkdir /INSTALLER
touch /INSTALLER/mountpoints
. /sbin/functions
cd /
initlocales
probedrives
probepartitions
choosemanualorauto
checkinstallationmodes
choosetargetdrive
createbiosbootandefipartitions
createrootpartition
createadditionalpartition
setroot
setotherlinux
setwindows
setefimanual
selectcontent
encryptornot
confirm
preparethedrive
encryptthedrive
formatrootpartitionandsetswapfile
formatotherlinuxpartitions
formatefimanual
installaaabaseandfixperms
setmountpoints
installfirstpackages
installkeyfile
fstab
crypttab
a11ysettings
#setpasswd
createregularuser
brlttyornot
startupmode
defaultlocale
noipv6
wired
wireless
settimezone
setlocales
displaydescornot
install
installfromiso
bindrootslint
passwords
postconfigure$(cat /tmp/distro)
mountefivarsandmovehome
bootingsetup
byebye
